require('dotenv').config();
const connectDB=require('./config/db');
const express=require('express');
const cors=require('cors');
const authroutes=require('../server/routes/authRoutes');
const userRoutes=require('../server/routes/usersRoutes');
const app=express();
connectDB();
app.use(cors({origin:'http://localhost:3000'}));
app.use(express.json());
app.use('/api/auth',authroutes);
app.use('/api/users',userRoutes);
const PORT=process.env.PORT || 5000;
app.listen(PORT,()=>console.log(`Server started on port ${PORT}`));